name: LegendPlugin
version: '${project.version}'
main: com.aquafun3d.legendplugin.Main
api-version: 1.18
authors: [ AquaFun3D ]
description: Bannsystem für PlayLegend


commands:
  ban:
    description: Bans a player
  unban:
    description: unbans a player